"""15+ curated Hyderabad infrastructure growth signals for seeding."""

GROWTH_SIGNALS = [
    # HMDA Layout Approvals
    {
        "signal_type": "hmda_layout",
        "title": "HMDA Layout Approval — Kokapet Node Zone",
        "source_url": "https://hmda.gov.in/layouts/kokapet-node",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2023-04-10",
        "center_lat": 17.3720,
        "center_lng": 78.3200,
        "radius_km": 5.0,
        "confidence": 0.95,
    },
    {
        "signal_type": "hmda_layout",
        "title": "HMDA Peripheral Ring Road Development Zone — Adibatla",
        "source_url": "https://hmda.gov.in/prr/adibatla",
        "source_type": "government",
        "status": "under_construction",
        "announced_date": "2022-11-20",
        "center_lat": 17.3200,
        "center_lng": 78.6100,
        "radius_km": 6.0,
        "confidence": 0.90,
    },
    {
        "signal_type": "hmda_layout",
        "title": "HMDA Pharma City Layout Zone — Mucherla",
        "source_url": "https://hmda.gov.in/pharmacitylayout",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2022-06-15",
        "center_lat": 17.1900,
        "center_lng": 78.3400,
        "radius_km": 8.0,
        "confidence": 0.92,
    },

    # NHAI / Highway Projects
    {
        "signal_type": "nhai_highway",
        "title": "NHAI NH-65 Six-Laning — Hyderabad to Pune Corridor",
        "source_url": "https://nhai.gov.in/nh65-sixlane",
        "source_type": "government",
        "status": "under_construction",
        "announced_date": "2021-09-01",
        "center_lat": 17.3850,
        "center_lng": 78.2500,
        "radius_km": 10.0,
        "confidence": 0.88,
    },
    {
        "signal_type": "nhai_highway",
        "title": "NHAI NH-44 Widening — Shadnagar to Hyderabad",
        "source_url": "https://nhai.gov.in/nh44-shadnagar",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2023-01-18",
        "center_lat": 17.0700,
        "center_lng": 78.2100,
        "radius_km": 8.0,
        "confidence": 0.85,
    },
    {
        "signal_type": "nhai_highway",
        "title": "ORR Phase II Extension — Patancheru to Sangareddy",
        "source_url": "https://hmda.gov.in/orr-phase2",
        "source_type": "government",
        "status": "announced",
        "announced_date": "2024-02-10",
        "center_lat": 17.5200,
        "center_lng": 78.0800,
        "radius_km": 7.0,
        "confidence": 0.70,
    },
    {
        "signal_type": "nhai_highway",
        "title": "NHAI Regional Ring Road (RRR) — Northern Arc",
        "source_url": "https://nhai.gov.in/rrr-north",
        "source_type": "government",
        "status": "under_construction",
        "announced_date": "2023-07-05",
        "center_lat": 17.6500,
        "center_lng": 78.4200,
        "radius_km": 12.0,
        "confidence": 0.82,
    },

    # HMRL Metro Extensions
    {
        "signal_type": "metro",
        "title": "HMRL Metro Phase 2 — Airport to Shamshabad Corridor",
        "source_url": "https://hmrl.co.in/phase2-airport",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2023-03-22",
        "center_lat": 17.2400,
        "center_lng": 78.4300,
        "radius_km": 4.0,
        "confidence": 0.94,
    },
    {
        "signal_type": "metro",
        "title": "HMRL Metro Phase 3 — Nagole to Ghatkesar Extension",
        "source_url": "https://hmrl.co.in/phase3-ghatkesar",
        "source_type": "government",
        "status": "announced",
        "announced_date": "2024-06-15",
        "center_lat": 17.4100,
        "center_lng": 78.6000,
        "radius_km": 3.0,
        "confidence": 0.68,
    },
    {
        "signal_type": "metro",
        "title": "HMRL Metro Corridor — Kokapet Financial District Node",
        "source_url": "https://hmrl.co.in/kokapet-node",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2023-08-30",
        "center_lat": 17.3750,
        "center_lng": 78.3300,
        "radius_km": 3.5,
        "confidence": 0.91,
    },

    # Industrial Parks & SEZs
    {
        "signal_type": "industrial_park",
        "title": "Hyderabad Pharma City — Mucherla SEZ",
        "source_url": "https://tsiic.telangana.gov.in/pharmacity",
        "source_type": "government",
        "status": "under_construction",
        "announced_date": "2021-12-01",
        "center_lat": 17.1800,
        "center_lng": 78.3600,
        "radius_km": 7.0,
        "confidence": 0.93,
    },
    {
        "signal_type": "industrial_park",
        "title": "Adibatla Aerospace & Defence Park — Phase 2",
        "source_url": "https://tsiic.telangana.gov.in/adibatla-aerospace",
        "source_type": "government",
        "status": "operational",
        "announced_date": "2020-08-15",
        "center_lat": 17.3300,
        "center_lng": 78.6200,
        "radius_km": 5.0,
        "confidence": 0.97,
    },
    {
        "signal_type": "industrial_park",
        "title": "Genome Valley Expansion — Shamirpet Biotech Cluster",
        "source_url": "https://tsiic.telangana.gov.in/genomevalley",
        "source_type": "government",
        "status": "operational",
        "announced_date": "2019-05-20",
        "center_lat": 17.5900,
        "center_lng": 78.5400,
        "radius_km": 6.0,
        "confidence": 0.98,
    },
    {
        "signal_type": "industrial_park",
        "title": "Fab City Semiconductor Zone — Patancheru",
        "source_url": "https://tsiic.telangana.gov.in/fabcity",
        "source_type": "government",
        "status": "approved",
        "announced_date": "2023-10-05",
        "center_lat": 17.5400,
        "center_lng": 78.1600,
        "radius_km": 6.0,
        "confidence": 0.89,
    },
    {
        "signal_type": "industrial_park",
        "title": "Sangareddy Industrial Corridor — Auto Manufacturing Zone",
        "source_url": "https://tsiic.telangana.gov.in/sangareddy-auto",
        "source_type": "government",
        "status": "under_construction",
        "announced_date": "2022-04-12",
        "center_lat": 17.6200,
        "center_lng": 78.0800,
        "radius_km": 8.0,
        "confidence": 0.84,
    },
    {
        "signal_type": "industrial_park",
        "title": "Ibrahimpatnam Logistics Hub — ORR Exit Zone",
        "source_url": "https://tsiic.telangana.gov.in/ibrahimpatnam-hub",
        "source_type": "government",
        "status": "announced",
        "announced_date": "2024-01-20",
        "center_lat": 17.2600,
        "center_lng": 78.7200,
        "radius_km": 4.0,
        "confidence": 0.72,
    },
]
